weather_icons = {
    "thunderstorm with light rain": "thunderstorms-rain.svg",
    "thunderstorm with rain": "thunderstorms-day-overcast-rain.svg",
    "thunderstorm with heavy rain": "thunderstorms-extreme-rain.svg",
    "light thunderstorm": "thunderstorms.svg",
    "thunderstorm": "thunderstorms.svg",
    "heavy thunderstorm": "thunderstorms-extreme.svg",
    "ragged thunderstorm": "thunderstorms.svg",
    "thunderstorm with light drizzle":"thunderstorms-rain.svg",
    "thunderstorm with drizzle": "thunderstorms-rain.svg",
    "thunderstorm with heavy drizzle": "thunderstorms-rain.svg",
    "light intensity drizzle": "overcast-drizzle.svg",
    "drizzle": "overcast-drizzle.svg",
    "heavy intensity drizzle": "overcast-drizzle.svg",
    "light intensity drizzle rain": "rain.svg",
    "drizzle rain": "rain.svg",
    "heavy intensity drizzle rain": "rain.svg",
    "shower rain and drizzle": "rain.svg",
    "heavy shower rain and drizzle": "rain.svg",
    "shower drizzle": "rain.svg",
    "light rain":"rain.svg",
    "moderate rain": "overcast-rain.svg",
    "heavy intensity rain": "overcast-rain.svg",
    "very heavy rain": "extreme-rain.svg",
    "extreme rain": "extreme-rain.svg",
    "freezing rain": "sleet.svg",
    "light intensity shower rain": "rain.svg",
    "shower rain": "rain.svg",
    "heavy intensity shower rain": "overcast-rain.svg",
    "ragged shower rain":"overcast-rain.svg",
    "light snow": "snow.svg",
    "snow": "snow.svg",
    "heavy snow": "extreme-snow.svg",
    "sleet": "sleet.svg",
    "light shower sleet": "sleet.svg",
    "shower sleet":"sleet.svg",
    "light rain and snow":"sleet.svg",
    "rain and snow":"overcast-sleet.svg",
    "light shower snow":"snow.svg",
    "shower snow":"overcast-snow.svg",
    "heavy shower snow": "overcast-snow.svg",
    "mist":"mist.svg",
    "smoke":"smoke.svg",
    "haze":"haze.svg",
    "sand/dust whirls":"dust.svg",
    "fog":"fog.svg",
    "sand":"dust.svg",
    "dust":"dust.svg",
    "volcanic ash":"dust-wind.svg",
    "squalls":"overcast.svg",
    "tornado":"hurricane.svg",
    "clear sky":"clear-day.svg",
    "few clouds":"partly-cloudy-day.svg",
    "scattered clouds":"partly-cloudy-day.svg",
    "broken clouds":"partly-cloudy-day.svg",
    "overcast clouds":"overcast.svg"
}